sudo: false
env:
  - CI=1
language: ruby
bundler_args: --without development debug profile
rvm:
  - 2.3.0
  - ruby-head
script: bin/test
before_install:
  - curl -o /tmp/vault.zip https://releases.hashicorp.com/vault/0.5.1/vault_0.5.1_linux_amd64.zip
  - unzip /tmp/vault.zip -d /tmp/
  - install -D -m 0755 /tmp/vault ./bin/vault
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3 # give xvfb some time to start
addons:
  apt:
    packages:
      - libqtwebkit-dev
matrix:
  allow_failures:
  - rvm: ruby-head
