sudo: false
env:
  - CI=1
language: ruby
bundler_args: --without development debug profile
rvm:
  - 2.1.5
  - 2.2.3
  - 2.3.0
script: script/test
before_install:
  - curl -o /tmp/vault.zip https://releases.hashicorp.com/vault/0.5.1/vault_0.5.1_linux_amd64.zip
  - unzip /tmp/vault.zip
  - install -D -m 0755 /tmp/vault ./bin/vault
addons:
  apt:
    packages:
      -  libwebkit-dev
